USE BUTTLER

CREATE TABLE CUSTOMER(
CUSTOMERID INT PRIMARY KEY IDENTITY,
CUSTOMERNAME NVARCHAR(100),
CUSTOMERGENDER NVARCHAR(50),
CUSTOMERPHONE INT
);

CREATE TABLE TABLES(
TABLEID INT PRIMARY KEY IDENTITY,
TABLENO INT,
CUSTOMERID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMERID) 
);



CREATE TABLE STAFFS(
STAFFSID INT PRIMARY KEY IDENTITY,
STAFFSTYPE NVARCHAR(100),
STAFFSLASTLOGIN NVARCHAR(100),
STAFFSSECURITYQA NVARCHAR(250)
);

CREATE TABLE STAFFDETAILS(
STAFFDETAILSID INT PRIMARY KEY IDENTITY,
STAFFNAME NVARCHAR(100),
STAFFGENDER NVARCHAR(100),
STAFFBIRTH DATE,
STAFFADDRESS NVARCHAR(250),
STAFFSID INT FOREIGN KEY REFERENCES STAFFS(STAFFSID)
);

CREATE TABLE FOOD(
FOODID INT PRIMARY KEY IDENTITY,
FOODTITLE NVARCHAR(100),
FOODDESCRIPTION NVARCHAR(250),
FOODPLATESIZE NVARCHAR(100)
);

CREATE TABLE ORDERMASTER(
ORDERMASTERID INT PRIMARY KEY IDENTITY,
CUSTOMERID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMERID),
TABLEID INT FOREIGN KEY REFERENCES TABLES(TABLEID),
STAFFSID INT FOREIGN KEY REFERENCES STAFFS(STAFFSID),
STAFFDETAILSID INT FOREIGN KEY REFERENCES STAFFDETAILS(STAFFDETAILSID),
FOODID INT FOREIGN KEY REFERENCES FOOD(FOODID)
);

CREATE TABLE ORDERITEMS (
ORDERITEMSID INT PRIMARY KEY IDENTITY,
FOODID INT FOREIGN KEY REFERENCES FOOD(FOODID),
ORDERMASTERID INT FOREIGN KEY REFERENCES ORDERMASTER(ORDERMASTERID)
);
